import { ProjectHeader } from "@/components/ProjectHeader";
import { Card } from "@/components/ui/card";
import { Calendar } from "lucide-react";
import { useState } from "react";
import { cn } from "@/lib/utils";

interface WeekReport {
  id: string;
  week: number;
  dateRange: string;
  status: "on-track" | "at-risk";
  statusEmoji: string;
  executiveSummary: string;
  accomplishments: string[];
  issuesRisks: { issues: string; risks: string; mitigation: string; };
  plansNextWeek: string[];
  upcomingMilestones: string[];
  changeSinceLastReport: string;
  projectHealth: string;
  reflection: string;
}

const weeklyReports: WeekReport[] = [
  { id: "week12", week: 12, dateRange: "Nov 2 – 8, 2025", status: "on-track", statusEmoji: "🟢", executiveSummary: "Everything is on track as the project nears closure. Deliverables are being completed and final revisions applied. Collaboration with peers has been constructive, and closure documentation is being drafted. This week underscored the importance of maintaining quality and consistency even as deadlines approach. All planned deliverables remain achievable within scope and timeline.", accomplishments: ["Reviewed and revised documentation for final submission.", "Conducted peer and stakeholder feedback sessions.", "Initiated closure documentation preparation."], issuesRisks: { issues: "No issues identified during this reporting period.", risks: "Timing constraints may impact final review depth.", mitigation: "Prioritized early submission of key deliverables to ensure adequate review time." }, plansNextWeek: ["Complete remaining deliverables and continue limited job-search activities.", "Conduct interview practice sessions with peers and professional stakeholders."], upcomingMilestones: ["Interview Practice – 11/08/2025: At Risk", "Stakeholder Feedback – 11/08/2025: On Track", "Prepare Closure Documents – 11/08/2025: On Track"], changeSinceLastReport: "No changes occurred during this reporting period.", projectHealth: "🟢 On Track", reflection: "This week brought clarity and focus as the project nears its official closure. Having completed most major deliverables, I shifted attention to reflection and refinement—a necessary pivot from execution to documentation and evaluation. Collaborating with peers reminded me that effective project management extends beyond individual deliverables to include communication, accountability, and adaptability. Preparing closure documentation required synthesizing weeks of work into actionable insights, a task that reinforced the value of structured record-keeping and regular reflection. Despite minor timing constraints, I remain confident in delivering high-quality final outputs. Looking ahead, I'm eager to apply the project management skills developed this semester to future professional initiatives." },
  { id: "week11", week: 11, dateRange: "Oct 26 – Nov 1, 2025", status: "on-track", statusEmoji: "🟢", executiveSummary: "As the project approaches closure, progress this week focused on refining deliverables, incorporating stakeholder feedback, and supporting peers through their own project milestones. Key achievements include completing revisions based on professional input, continuing limited job-search activities, and drafting preliminary closure documentation. The overall trajectory remains on track, with all scheduled milestones achievable within scope and timeline.", accomplishments: ["Revised project documentation based on stakeholder feedback.", "Supported peers through their project milestones with structured reviews.", "Began drafting closure documentation to capture lessons learned and final deliverables."], issuesRisks: { issues: "No issues identified during this reporting period.", risks: "End-of-course transitions may lead to reduced availability for final tasks.", mitigation: "Prioritized early completion of remaining deliverables and scheduled clear task timelines." }, plansNextWeek: ["Complete remaining deliverables and continue limited job-search activities.", "Conduct interview practice sessions with peers and professional stakeholders."], upcomingMilestones: ["Interview Practice – 11/08/2025: At Risk", "Stakeholder Feedback – 11/08/2025: On Track", "Prepare Closure Documents – 11/08/2025: On Track"], changeSinceLastReport: "No changes occurred during this reporting period.", projectHealth: "🟢 On Track", reflection: "As the project nears its conclusion, this week's focus was on finalizing deliverables and supporting peers through constructive feedback. I began drafting closure documentation and outlining interview sessions with a peer, a professor, and a manager from CHASE. Collaborating with classmates reinforced key project management principles such as alignment between goals, values, and execution. Although progress slowed slightly due to end-of-course transitions, this phase highlights how far I've come—growing from project planning and execution to reflection and mentorship. It's rewarding to see both personal and professional development emerge through consistent engagement and perseverance." },
  { id: "week10", week: 10, dateRange: "Oct 19 – 25, 2025", status: "on-track", statusEmoji: "🟢", executiveSummary: "The project remains on track, with steady progress made across key deliverables. The résumé has been finalized and stakeholder feedback incorporated, resulting in improved application readiness. Several job openings have been identified for targeted applications, marking the transition from planning to execution. Communication with stakeholders this week provided valuable insight into maintaining consistent follow-through and confidence in the application process.", accomplishments: ["Conducted focused job hunting and identified multiple potential openings.", "Completed résumé construction and tailored it to professional standards.", "Held feedback sessions with stakeholders to refine job search strategies and résumé quality."], issuesRisks: { issues: "No issues identified during this reporting period.", risks: "Minor scheduling delays may occur due to the application process workload.", mitigation: "Maintain structured application timelines and continue proactive communication with stakeholders." }, plansNextWeek: ["Continue targeted job applications based on identified opportunities.", "Prepare for peer feedback and stakeholder consultations."], upcomingMilestones: ["Resume Finalization & Peer Feedback – 10/25/2025: Completed", "Job Applications Submission – 11/01/2025: On Track", "Draft Status Report – 11/01/2025: On Track"], changeSinceLastReport: "No changes occurred during this reporting period.", projectHealth: "🟢 On Track", reflection: "This week marked a critical transition—moving from preparation into execution. Finalizing my résumé required synthesizing feedback from multiple sources, balancing clarity with professionalism. Identifying job opportunities felt both empowering and slightly overwhelming, but this process reinforced the importance of staying organized and prioritizing roles aligned with my career goals. Stakeholder feedback reminded me that confidence is a skill developed through practice and iteration. I'm encouraged by the progress made and energized to take the next steps, applying to roles to turn preparation into action." },
  { id: "week9", week: 9, dateRange: "Oct 12 – 18, 2025", status: "at-risk", statusEmoji: "🟡", executiveSummary: "Project progress slowed this week due to reduced availability and shifted priorities, resulting in an At Risk status. While key deliverables such as job hunting research and résumé construction advanced, stakeholder engagement and documentation updates fell behind schedule. Despite these delays, the foundational work completed this week positions the project to recover during the next reporting period through focused effort and improved time management.", accomplishments: ["Continued job hunting research and analyzed target job requirements.", "Advanced résumé construction and customization efforts.", "Conducted initial self-assessment to guide application preparation."], issuesRisks: { issues: "Reduced availability and competing priorities slowed progress on stakeholder engagement and documentation.", risks: "Continued delays may impact the quality and timeliness of upcoming deliverables.", mitigation: "Re-prioritized tasks and scheduled additional time blocks for project work in the upcoming week." }, plansNextWeek: ["Complete résumé construction and finalize application materials.", "Re-engage with stakeholders for feedback and guidance.", "Finalize draft status report and update project documentation."], upcomingMilestones: ["Resume Finalization & Peer Feedback – 10/25/2025: At Risk", "Job Applications Submission – 11/01/2025: At Risk", "Draft Status Report – 11/01/2025: At Risk"], changeSinceLastReport: "Project status changed from On Track to At Risk due to reduced progress.", projectHealth: "🟡 At Risk", reflection: "This week served as a reminder that project success requires consistent focus and intentional prioritization. While external factors contributed to the slowdown, taking ownership of the situation and adjusting plans moving forward is essential. The work completed—particularly in résumé development and job analysis—demonstrates progress, but the delay in stakeholder communication highlighted the importance of maintaining engagement even during busy periods. I'm committed to recovering this week and ensuring that upcoming deliverables meet the project's high standards through structured effort and stakeholder collaboration." },
  { id: "week8", week: 8, dateRange: "Oct 5 – 11, 2025", status: "on-track", statusEmoji: "🟢", executiveSummary: "The project continues to perform well with only minor deviations from the planned schedule. This week's focus centered on career platform research and résumé development, both of which progressed as anticipated. Engagement with stakeholders provided clarity on best practices for professional documents and job application strategies. Overall project health remains strong, with all major milestones on track for completion within the established timeline.", accomplishments: ["Conducted research across LinkedIn, Indeed, Handshake, and Career Center platforms.", "Analyzed target job requirements to inform customized résumé development.", "Engaged with stakeholders to gather feedback on job search strategies."], issuesRisks: { issues: "No issues identified during this reporting period.", risks: "Scheduling constraints may slightly impact task completion timelines.", mitigation: "Maintained flexibility in task execution and re-prioritized work as needed to stay on track." }, plansNextWeek: ["Continue résumé construction and customization for selected job opportunities.", "Deepen research into target roles and companies to refine application strategies.", "Hold additional stakeholder consultations for feedback on draft materials."], upcomingMilestones: ["Resume Creation – 10/11/2025: On Track", "Job Requirements Analysis – 10/11/2025: On Track", "Resume Finalization & Peer Feedback – 10/25/2025: On Track"], changeSinceLastReport: "No changes occurred during this reporting period.", projectHealth: "🟢 On Track", reflection: "This week reinforced the importance of structured research and targeted preparation. Analyzing career platforms revealed unique strengths: LinkedIn's professional networking depth, Indeed's breadth of listings, and Handshake's tailored student focus. Understanding these nuances helps me approach job searching more strategically rather than reactively. Additionally, crafting a résumé tailored to specific roles reminded me that quality matters far more than quantity in the application process. Stakeholder feedback this week was invaluable, offering insights that will shape not only my résumé but also my overall approach to professional communication." },
  { id: "week7", week: 7, dateRange: "Sep 28 – Oct 4, 2025", status: "on-track", statusEmoji: "🟢", executiveSummary: "The project remains on track, with progress aligning closely with planned milestones. This week's efforts concentrated on initiating résumé construction, job requirements analysis, and engagement with career center resources. Research into ISC2 membership confirmed its relevance to long-term career goals, particularly for cybersecurity roles. All key deliverables are progressing as expected, and stakeholder communication remains consistent.", accomplishments: ["Began résumé construction with a focus on professional clarity and alignment with target roles.", "Analyzed job requirements for multiple cybersecurity and business analyst positions.", "Researched ISC2 mission, membership benefits, and career center tools."], issuesRisks: { issues: "No issues identified during this reporting period.", risks: "No risks identified during this reporting period.", mitigation: "N/A" }, plansNextWeek: ["Continue résumé construction and tailor document to specific job opportunities.", "Deepen job hunting research and identify target companies.", "Engage with stakeholders for feedback on draft résumé and job search strategies."], upcomingMilestones: ["Resume Creation – 10/11/2025: On Track", "Job Requirements Analysis – 10/11/2025: On Track", "CC Research & ISC2 Account Creation – 10/11/2025: Completed"], changeSinceLastReport: "No changes occurred during this reporting period.", projectHealth: "🟢 On Track", reflection: "This week felt productive and forward-focused. Starting the résumé construction process required balancing professional tone with authenticity—showcasing skills and experience without exaggeration. Researching job requirements illuminated patterns in what employers value, particularly around analytical thinking, communication, and adaptability. Exploring ISC2's mission reminded me why cybersecurity remains a compelling long-term career path: the opportunity to contribute to a field that protects critical systems and promotes global security standards. I'm encouraged by the progress made and confident in maintaining this momentum moving forward." },
  { id: "week6", week: 6, dateRange: "Sep 21 – 27, 2025", status: "at-risk", statusEmoji: "🟡", executiveSummary: "Due to sudden health issues, project progress slowed and fell behind the planned schedule. Essential research tasks were completed, including career platform comparisons and initial exploration of ISC2 membership benefits. However, several deliverables requiring sustained focus were delayed. This setback highlights the importance of schedule flexibility and risk mitigation planning. With adjusted priorities and improved health, the project is expected to recover during the next reporting period.", accomplishments: ["Completed career platform research comparing LinkedIn, Indeed, Handshake, and Career Center.", "Researched ISC2 mission, membership tiers, and professional benefits.", "Maintained communication with stakeholders despite reduced project hours."], issuesRisks: { issues: "Sudden health issues reduced available project hours significantly.", risks: "Delayed deliverables may impact subsequent milestones if not addressed promptly.", mitigation: "Focused on flexible research-based activities requiring less time sensitivity while maintaining project momentum." }, plansNextWeek: ["Create and verify ISC2 account and Career Center (CC) profile.", "Review past application documents and conduct a self-assessment.", "Select targeted jobs for résumé customization."], upcomingMilestones: ["Resume Creation – 9/27/2025: On Track", "Job Requirements Analysis – 10/04/2025: On Track", "CC Research & ISC2 Account Creation – 10/04/2025: At Risk"], changeSinceLastReport: "No changes occurred during this reporting period.", projectHealth: "🟡 At Risk", reflection: "This week's progress began under challenging health circumstances, but consistent effort ensured that essential tasks were completed. Analyzing career platforms revealed distinct advantages: Handshake as the most student-oriented, LinkedIn as the most professional, and Indeed as a balanced option. ISC2's mission to promote cybersecurity worldwide aligns closely with my long-term career goals. Despite reduced hours, the work completed reflects both commitment and adaptability." }
];

const StatusReport = () => {
  const [expandedWeeks, setExpandedWeeks] = useState<Set<string>>(new Set(["week12"]));
  const toggleWeek = (weekId: string) => { setExpandedWeeks(prev => { const newSet = new Set(prev); if (newSet.has(weekId)) { newSet.delete(weekId); } else { newSet.add(weekId); } return newSet; }); };
  const toggleAll = () => { if (expandedWeeks.size === weeklyReports.length) { setExpandedWeeks(new Set()); } else { setExpandedWeeks(new Set(weeklyReports.map(w => w.id))); } };
  const scrollToWeek = (weekId: string) => { const element = document.getElementById(weekId); if (element) { const offset = 160; const elementPosition = element.getBoundingClientRect().top; const offsetPosition = elementPosition + window.pageYOffset - offset; window.scrollTo({ top: offsetPosition, behavior: 'smooth' }); } };

  return (
    <div className="min-h-screen bg-background">
      <ProjectHeader />
      <nav className="sticky top-[88px] z-40 bg-card/95 backdrop-blur-sm border-b border-border shadow-sm">
        <div className="container mx-auto px-6 py-3">
          <div className="flex items-center gap-4 overflow-x-auto scrollbar-hide">
            <button onClick={toggleAll} className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium text-muted-foreground transition-colors hover:text-foreground hover:bg-secondary whitespace-nowrap">
              <Calendar className="h-4 w-4" />{expandedWeeks.size === weeklyReports.length ? "Collapse All" : "Expand All"}
            </button>
            <div className="h-6 w-px bg-border" />
            {weeklyReports.map((report) => (<button key={report.id} onClick={() => scrollToWeek(report.id)} className="px-4 py-2 rounded-lg text-sm font-medium text-muted-foreground transition-colors hover:text-foreground hover:bg-secondary whitespace-nowrap">Week {report.week}</button>))}
          </div>
        </div>
      </nav>
      <main className="container mx-auto px-6 py-8 max-w-5xl">
        <div className="mb-8"><h1 className="text-4xl font-bold text-foreground mb-3">Weekly Status Reports</h1><p className="text-lg text-muted-foreground">Business-Aligned Job Hunt – Progress tracking from Week 6 to Week 12</p></div>
        <div className="space-y-4">
          {weeklyReports.map((report) => (
            <Card key={report.id} id={report.id} className="overflow-hidden transition-all duration-300">
              <button onClick={() => toggleWeek(report.id)} className="w-full text-left bg-gradient-to-r from-primary/10 to-primary/5 hover:from-primary/15 hover:to-primary/10 transition-colors p-6 flex items-center justify-between">
                <div className="flex items-center gap-4"><span className="text-2xl">{report.statusEmoji}</span><div><h2 className="text-xl font-semibold text-foreground">Week {report.week} Status Report</h2><p className="text-sm text-muted-foreground mt-1">{report.dateRange} – {report.status === "on-track" ? "On Track" : "At Risk"}</p></div></div>
                <div className={cn("transition-transform duration-300 text-xl", expandedWeeks.has(report.id) ? "rotate-180" : "")}>▼</div>
              </button>
              {expandedWeeks.has(report.id) && (
                <div className="p-6 space-y-6 animate-in fade-in slide-in-from-top-2 duration-300">
                  <div><h3 className="text-lg font-semibold text-foreground mb-2 flex items-center gap-2">📋 Executive Summary</h3><p className="text-muted-foreground leading-relaxed">{report.executiveSummary}</p></div>
                  <div><h3 className="text-lg font-semibold text-foreground mb-2 flex items-center gap-2">✅ Accomplishments This Week</h3><ul className="list-disc list-inside space-y-1 text-muted-foreground">{report.accomplishments.map((item, idx) => (<li key={idx}>{item}</li>))}</ul></div>
                  <div><h3 className="text-lg font-semibold text-foreground mb-2 flex items-center gap-2">⚠️ Issues & Risks / Mitigations</h3><div className="space-y-2 text-muted-foreground"><p><strong className="text-foreground">Issues:</strong> {report.issuesRisks.issues}</p><p><strong className="text-foreground">Risks:</strong> {report.issuesRisks.risks}</p><p><strong className="text-foreground">Mitigation:</strong> {report.issuesRisks.mitigation}</p></div></div>
                  <div><h3 className="text-lg font-semibold text-foreground mb-2 flex items-center gap-2">📅 Plans for Next Week</h3><ul className="list-disc list-inside space-y-1 text-muted-foreground">{report.plansNextWeek.map((item, idx) => (<li key={idx}>{item}</li>))}</ul></div>
                  <div><h3 className="text-lg font-semibold text-foreground mb-2 flex items-center gap-2">🎯 Upcoming Milestones</h3><ul className="list-disc list-inside space-y-1 text-muted-foreground">{report.upcomingMilestones.map((item, idx) => (<li key={idx}>{item}</li>))}</ul></div>
                  <div><h3 className="text-lg font-semibold text-foreground mb-2 flex items-center gap-2">🔄 Change Since Last Report</h3><p className="text-muted-foreground">{report.changeSinceLastReport}</p></div>
                  <div><h3 className="text-lg font-semibold text-foreground mb-2 flex items-center gap-2">💚 Project Health</h3><p className="text-muted-foreground font-medium">{report.projectHealth}</p></div>
                  <div className="pt-4 border-t border-border"><h3 className="text-lg font-semibold text-foreground mb-2 flex items-center gap-2">💭 Reflection</h3><p className="text-muted-foreground leading-relaxed">{report.reflection}</p></div>
                </div>
              )}
            </Card>
          ))}
        </div>
      </main>
    </div>
  );
};

export default StatusReport;
